### ISSUE TITLE
Mutliple users watching the same stream may cause issues

### ISSUE THREAD

**Issue by tomouchuu** [haishinio/haishin#4]
In our first beta test there was some weirdness with the transcriptions. I _think_ it was down to multiple sessions all looking at the same file with different start-times and durations but not certain.

Probably main priority before sharing with wider group

**Comment by tomouchuu** [comment]
So at least doing some local testing I can cause the issue. I believe it is down to trying to run more than one command of ffmpeg.wasm.

I guess the best way would be to move this out into a function/event, so it spawns a completely new instance for each request check? Will ponder

**Comment by tomouchuu** [comment]
Not fixed, still issues probably due to 
```
Error: ffmpeg.FS('readFile', 'stream.wav') error. Check if the path exists
haishin       |     at Object.FS (/app/node_modules/@ffmpeg/ffmpeg/src/createFFmpeg.js:218:17)
haishin       |     at /app/.next/server/chunks/190.js:116:97
haishin       |     at async file:///app/node_modules/p-queue/dist/index.js:118:36
```

**Comment by tomouchuu** [comment]
Not sure if 010795a was the actual fix, but it did go someway to fixing locally and stopping the memory leaks. Will be interesting to see what happens on the vps
